### ISSUE TITLE
Migrate TCK Generation CI job to https://ci.eclipse.org/rest/   

### ISSUE THREAD

**Issue by alwin-joseph** [jakartaee/rest#1083]
The migrated jaxrs TCK is currently built and bundled using CI job  https://ci.eclipse.org/jakartaee-tck/job/jakarta-rest-tck-build that exists in jakartaee-tck CI and the eftl licensed bundle copied to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/. It also creates SHASUM file for each newly generated TCK bundle.

Ideally the tck building job should be present at https://ci.eclipse.org/rest/ CI instance, and the bundle copied over to jaxrs-api project owned Eclipse directory (probably a new folder at https://download.eclipse.org/ee4j/ ).

The jobs https://ci.eclipse.org/jakartaee-tck/job/jakarta-rest-tck-build and https://ci.eclipse.org/jakartaee-tck/job/jakarta-rest-tck-build-epl may be recreated at https://ci.eclipse.org/rest with any  expected modifications.

**Comment by alwin-joseph** [comment]
1. Get new folder created at https://download.eclipse.org/ee4j/  as https://download.eclipse.org/ee4j/jaxrs . We can check if the below command works when run in a CI job. If it does not we would need help from Eclipse infra team(use bugzilla) for creating new directory at [/home/data/httpd/download.eclipse.org/ee4j/jaxrs
](https://download.eclipse.org/ee4j/jaxrs)

`ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null genie.jakartaee-tck@projects-storage.eclipse.org mkdir -p /home/data/httpd/download.eclipse.org/ee4j/jaxrs`

2. Run `mvn clean install` from $WORKSPACE(/jaxrs-api) The Job can be a maven project where mvn command is triggered directly or  run the mvn command in shell script separately

3. In shell script execute below to generate EFTL bundle. 
```
cd $WORKSPACE/jaxrs-tck-docs/
sh tckbundle.sh
```

Note: To generate EPL bundle below can be executed
```
cd $WORKSPACE/jaxrs-tck-docs/
sh tckbundle.sh epl
```

The tckbundle.sh accepts the bundle license as first argument(eftl or epl). By default it generates EFTL bundle if no argument is passed.

4. The bundle will be generated at  $WORKSPACE/bundle. The same will need to be copied to any folder within https://download.eclipse.org/ee4j/jaxrs .

5. Generate SHASUM file and copy the same to https://download.eclipse.org/ee4j/jaxrs

**Comment by spericas** [comment]
Any volunteers to do this?

**Comment by mkarg** [comment]
Why do we need a new job? Shouldn't we build and publish the TCK as part of the existing API job?

**Comment by alwin-joseph** [comment]
> Why do we need a new job? Shouldn't we build and publish the TCK as part of the existing API job?

There are more tasks that need to be done for the TCKs apart from the usual mvn install.

Below can be  accomplished by running jaxrs-tck-docs/tckbundle.sh. 
- 2 types of TCK bundles need to be generated differentiated by the LICENSE file & the name of the file - EPL & EFTL. tckbundle.sh accepts epl/eftl as first argument for 2 different bundles. 
- The TCKs are bundled as zip files with TCK documentation and TCK jar, see latest bundle generated at https://ci.eclipse.org/jakartaee-tck/job/jakarta-rest-tck-build/lastSuccessfulBuild/artifact/bundle/jakarta-restful-ws-tck-3.1.0.zip (EFTL bundle)

Below are accomplished via the Jenkins job currently.
- The TCK bundles(EPL & EFTL) need to be copied to an Eclipse download location (https://download.eclipse.org/ee4j/jaxrs yet to be created)
- The SHASUM of the zip bundle need to be generated and copied to the same download location 

If all the above can be done via the API job we do not need another Jenkins job. Along with this, the latest TCK jar should be uploaded to the maven repository.

**Comment by alwin-joseph** [comment]
It would be great if this issue is addressed sooner so that the next releases(post-3.1.1) of REST TCK (EFTL & EPL) can be done at REST Jenkins.

**Comment by alwin-joseph** [comment]
New folder has been created at https://download.eclipse.org/ee4j/restful-ws to copy the restful-ws TCK, gitlab issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4440 .

New Jenkins job https://ci.eclipse.org/rest/job/TCK_EFTL_build_and_stage can be used to build and stage new TCK bundles from main branch.

**Comment by jim-krueger** [comment]
Awesome!   Thanks Alvin!!
