### ISSUE TITLE
Move this repo to https://github.com/jakartaee

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/rest#1086]
In the steering committee we voted to move all specification projects from eclipse-ee4j to jakartaee. As such this repo should move too in due time.

Moving is fairly automatic, and redirects will be automatically put in place from the current location here to the new location.

If there is a +1 for this (lazy or direct) I'd like to move this repo soon.

**Comment by mkarg** [comment]
Can you please link to a web site where that decision can be found? Thanks.

Is this really decided by the committers? We had not been asked for the original location nor can we trigger the technical move.

I do not see a benefit for us, but I actually never liked the original location either, so I vote 0.

When you do the move then please also fix all the Jenkins Jobs and links in any locations that point here. Thanks.

**Comment by jansupol** [comment]
From all the steps we want to do and we are obliged to do with our Jakarta REST repository, moving the GitHub coordinates seems like the least urgent task. Is doing so around the release date at the time of finishing the last changes in the project a good timing?

**Comment by spericas** [comment]
@arjantijms I see no problem, but perhaps we should wait until 3.1 is out in case this causes any unforeseen problems. It shouldn't be long.

**Comment by bondolo** [comment]
The Javadoc API link in the sidebar on `https://jakartaee.github.io/rest/` is broken and still points to the old `https://eclipse-ee4j.github.io/jaxrs-api/apidocs` location. The correct landing page, `https://jakartaee.github.io/rest/apidocs/` does exist but the links on that page also still point to the old site.

**Comment by bondolo** [comment]
The user guide at `https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/index.html` doesn't appear to have a new location in the `https://jakartaee.github.io/rest/` site yet.

**Comment by jansupol** [comment]
Constant vigilance. I am quite surprised.

**Comment by mkarg** [comment]
AFAIK this issue can be closed as the repo was already moved?
