### ISSUE TITLE
TCK tests using JAXB without xml_binding tag

### ISSUE THREAD

**Issue by starksm64** [jakartaee/rest#1109]
In looking at running the TCK against a Core Profile implementation that does not include JAXB support, I found the following tests executing even when excludedGroups=xml_binding was specified:

ee.jakarta.tck.ws.rs.api.rs.core.linkjaxbadapter.JAXRSClientIT#marshallTest/unmarshallTest

**Comment by brideck** [comment]
I saw your update, but it looks like you still didn't remove `ee.jakarta.tck.ws.rs.spec.provider.standardhaspriority.JAXRSClientIT.*` from the list of what's run for Core Profile.  From looking at the test class, I can see that an effort was made to mark a single test method as requiring JAXB, but there's too much usage of `JAXBElement` throughout the test application so it can't initialize, at least in OL.

**Comment by brideck** [comment]
I'm also not sure that the proposed/implemented solution is the best one for the `xml_binding` issue.  That is not strictly a Core Profile problem, XML Binding is optional full stop, not just in certain profiles, and the correct set of tests really needs to be identified in the TCK itself.

**Comment by starksm64** [comment]
So the ee.jakarta.tck.ws.rs.spec.provider.standardhaspriority.JAXRSClientIT.readWriteJaxbProviderTest test that uses JAXBElement is marked with @Tag("xml_binding"). I wonder if the JAXBElement reference in that test method was changed to a fully qualified class name and not in the imports if that would avoid attempting to load JAXBElement during initialization.

**Comment by starksm64** [comment]
Looking at how the compiler handles imports, it seems that it makes no difference whether a class is explicitly imported or used as a fully qualified type. This means that xml_binding tests need to be factored into a separate artifacts.

**Comment by brideck** [comment]
Right, in this case it's not enough to just mark the individual test method.  The application itself has further references to JAXBElement.  In the case of OL, it's the reference in `ee.jakarta.tck.ws.rs.spec.provider.standardhaspriority.Resource` that causes the servlet to fail to initialize.

**Comment by starksm64** [comment]
So another workaround that will work for any profile would be to simply attach the jaxb api jar to the test archive using
an org.jboss.arquillian.container.test.spi.client.deployment.ApplicationArchiveProcessor implementation. There is an example of this in this test project:

https://github.com/jakartaredhat/jaxbtestjar

We discuss tomorrow in the tck call.

**Comment by scottmarlow** [comment]
Could a  committer please add the TCK Challenge to this issue.

**Comment by scottmarlow** [comment]
Note that the XML Binding use in REST in EE 9.1, had keyword.properties entries to allow XML Binding tests to be excluded.

**Comment by brideck** [comment]
Here's our proposed TCK update: https://github.com/jakartaee/rest/pull/1117

I've verified that this successfully excludes the remaining tests with XML Binding dependencies and we get the expected results with Open Liberty.  It would be a good thing for another implementation to also verify that everything works as expected.

**Comment by starksm64** [comment]
That PR works for WildFly.

**Comment by brideck** [comment]
Groovy.  So if we can get the REST group to formally approve this challenge, we can go ahead and get that update merged.

**Comment by spericas** [comment]
I'd like @jansupol to comment on this issue, I believe he is back from vacation next week.

**Comment by brideck** [comment]
For reference, this is the set of tests that was previously marked as `xml_binding` when this was part of the Platform TCK.
```
com/sun/ts/tests/jaxrs/jaxrs21/ee/sse/sseeventsource = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional xml_binding
com/sun/ts/tests/jaxrs/jaxrs21/ee/sse/sseeventsink = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional xml_binding
com/sun/ts/tests/jaxrs/api/rs/core/linkjaxbadapter = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional xml_binding
com/sun/ts/tests/jaxrs/spec/filter/interceptor = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional xml_binding
com/sun/ts/tests/jaxrs/spec/provider/overridestandard = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional xml_binding
com/sun/ts/tests/jaxrs/spec/provider/standardhaspriority = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional  xml_binding
com/sun/ts/tests/jaxrs/spec/provider/standardnotnull = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional xml_binding
com/sun/ts/tests/jaxrs/spec/provider/standardwithxmlbinding = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional xml_binding
com/sun/ts/tests/jaxrs/spec/provider/jaxbcontext = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional xml_binding
com/sun/ts/tests/jaxrs/spec/client/typedentitieswithxmlbinding = jaxrs javaee_optional jaxrs_web_profile javaee_web_profile_optional xml_binding
```

To summarize, the proposed change here restores the tags that were not ported over from the Platform TCK for the two SSE test classes and expands the tagging for the `standardhaspriority` test that was previously excluded.  The `standardhaspriority` test could be refactored in a future release so that only the test actually intending to use XML Binding need be excluded.

**Comment by spericas** [comment]
@starksm64 I believe @jansupol should be back from vacation tomorrow. Will ping him.

**Comment by Emily-Jiang** [comment]
Addressed by #1117

**Comment by jansupol** [comment]
I have commented on the PR. One test class seems irrelevant to the missing JAX-B to me.

**Comment by jansupol** [comment]
> One test class seems irrelevant to the missing JAX-B to me.

I was wrong, I approved the PR.

**Comment by starksm64** [comment]
So at this point a new service release of the tck is needed and a PR to update the jakarta.ee page via the https://github.com/jakartaee/specifications/ repo.

**Comment by jim-krueger** [comment]
@starksm64 Can this issue be closed?

**Comment by starksm64** [comment]
Yes
