### ISSUE TITLE
Prepare Jakarta REST release 3.1.1 after updating dependencies

### ISSUE THREAD

**Issue by spericas** [jakartaee/rest#1110]
Consider preparing a 3.1.1 release if/when new versions of JAXB and activation are available.

**Comment by jansupol** [comment]
It is used for the tests, only, though.

**Comment by spericas** [comment]
@jansupol Do you know if we can update this now?

**Comment by jamezp** [comment]
The spec does [state](Jakarta® XML Binding, Version 3.0 https://jakarta.ee/specifications/xml-binding/3.0/)
> Jakarta® XML Binding, Version 3.0 https://jakarta.ee/specifications/xml-binding/3.0/

However, I see failing platform signature TCK tests due to the `jakarta.ws.rs.core.Link$JaxbAdapter`. I think it makes sense to require 4.0, but that feels strange in a micro release.

**Comment by jansupol** [comment]
> but that feels strange in a micro release.

What do you mean by micro release? Microprofile is aligned with EE 9, and for microservices, the JAXB should be purely optional.

**Comment by jansupol** [comment]
> The spec does [state](Jakarta® XML Binding, Version 3.0 https://jakarta.ee/specifications/xml-binding/3.0/)

I could not find it in the[ spec document](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.pdf). The API already depends on JAX-B 4.0 Final API, Only the test dependency is on 4.0.0-M4. Do we need to release the new API because of the test dependency?

> I see failing platform signature TCK tests due to the jakarta.ws.rs.core.Link$JaxbAdapte

The platform TCK/signature tests are not final, yet. There is still time to update the signature records.

**Comment by jamezp** [comment]
> > but that feels strange in a micro release.
> 
> What do you mean by micro release? Microprofile is aligned with EE 9, and for microservices, the JAXB should be purely optional.

I just meant it seems weird to migrate to Jakarta XML Binding 4.0 in a 3.1.1 release. A major or minor bump in the version would make more sense in general. However, I understand that is not possible.
