### ISSUE TITLE
Compatibility Certification Request for RESTEasy 6.1.0.Beta2

### ISSUE THREAD

**Issue by jamezp** [jakartaee/rest#1111]
* [x]  Organization Name ("Organization") and, if applicable, URL
  Red Hat, Inc
* [x]  Product Name, Version and download URL (if applicable)
  RESTEasy 6.1.0.Beta2, see TCK Result Summary for the download links
* [x]  Specification Name, Version and download URL
  [Jakarta RESTful Web Services 3.1](https://jakarta.ee/specifications/restful-ws/3.1/)
* [x]   TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta RESTful Web Services TCK 3.1.0](https://download.eclipse.org/jakartaee/restful-ws/3.1/jakarta-restful-ws-tck-3.1.0.zip), SHA-256: ea8cd6cc857af55f19468bbb09e8a30f41c60e8f7413a093e7007c3902a49070
* [x]  Public URL of TCK Results Summary
  [TCK results summary](https://github.com/resteasy/certifications/blob/main/jakarta-rest-3.1/6.1.0.Beta1/jakarta-rest-tck.adoc)
* [x]  Any Additional Specification Certification Requirements
  None
* [x]  Java runtime used to run the implementation
  JDK 11.0.2+9
* [x]  Summary of the information for the certification environment, operating system, cloud, ...
  Linux
* [x]  By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
* [x]  By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by mkarg** [comment]
I would like to repeat the test on my own machine. Is there a public document listing the needed commands, or is there a POM that I could simply execute?

**Comment by jamezp** [comment]
@mkarg Sure thing. This is the project we're using https://github.com/resteasy/resteasy-tck-runner. The README should be straight forward, but please feel free to ping me if you've got questions.

**Comment by mkarg** [comment]
I confirm that the product passes the TCK suite successfully:
>Tests run: 2796, Failures: 0, Errors: 0, Skipped: 59

**Comment by jamezp** [comment]
Thank you @mkarg!

**Comment by mkarg** [comment]
> Is there any update on this?

In what regard? What do you expect to happen?

**Comment by arjantijms** [comment]
I think that the request needs to be accepted and then closed. See e.g. https://github.com/jakartaee/faces/issues/1673

**Comment by arjantijms** [comment]
A committer I assert this is complete and therefor accepted.

**Comment by jamezp** [comment]
Thank you all. TBH I wasn't too sure what to expect with the exception of having RESTEasy listed as a compatible implementation :)

**Comment by jansupol** [comment]
I remember there was a need to send an email to tck@eclipse.org with "Approval to claim Jakarta RESTful Web Services 3.1 compatibility for <project name>" subject, so I was not sure who is about to react to this request...
