### ISSUE TITLE
ee.jakarta.tck.ws.rs.ee.rs.container.requestcontext.JAXRSClientIT should be excluded from Core Profile executions

### ISSUE THREAD

**Issue by brideck** [jakartaee/rest#1120]
The application used for the ee.jakarta.tck.ws.rs.ee.rs.container.requestcontext tests has an explicit dependency on Servlet, which is not part of Core Profile.

https://github.com/jakartaee/rest/blob/master/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/requestcontext/Resource.java#L19

There should be an exclusion group that includes these tests for vendors certifying Core Profile in the absence of servlet.

**Comment by brideck** [comment]
Per the discussion on the TCK call earlier today, the proposal would be to tag this one as belonging to a "servlet" group.

**Comment by alwin-joseph** [comment]
New TCK bundle is generated at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.1.zip with this resolved.
