### ISSUE TITLE
ee.jakarta.tck.ws.rs.ee.rs.core.securitycontext.basic.JAXRSBasicClientIT should be excluded from Core Profile executions

### ISSUE THREAD

**Issue by brideck** [jakartaee/rest#1121]
These tests are dependent on Authorization being enabled on the server under test.  Since no security specifications are a part of Core Profile, these tests should be part of an exclusion group for vendors certifying Core Profile in the absence of security.

https://github.com/jakartaee/rest/blob/master/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.java

**Comment by brideck** [comment]
Per the discussion on the TCK call earlier today, the proposal would be to tag this one as belonging to a "security" group.

**Comment by alwin-joseph** [comment]
> Sorry, I left a class out of this issue that needs to be excluded -- https://github.com/jakartaee/rest/blob/master/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/requestcontext/security/JAXRSClientIT.java
> 
> My apologies for the omission.

Sure no issues. Can you please review https://github.com/jakartaee/rest/pull/1124 .

**Comment by alwin-joseph** [comment]
@starksm64 @brideck 
TCK bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.1.zip is updated with changes in PR https://github.com/jakartaee/rest/pull/1124.

**Comment by brideck** [comment]
New TCK bundle looks good to me now.

My test count for Core with all of the excludes in place is 2647.

**Comment by starksm64** [comment]
I see 2654 with the latest 3.1.1 staged bundle:

```
[INFO] Results:
[INFO] 
[WARNING] Tests run: 2654, Failures: 0, Errors: 0, Skipped: 59
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:34 min
[INFO] Finished at: 2022-07-19T18:23:37-05:00
[INFO] ------------------------------------------------------------------------
```

@brideck Do you have your pom.xml somewhere I can look at the configuration?

**Comment by brideck** [comment]
> @brideck Do you have your pom.xml somewhere I can look at the configuration?

The difference is that I have the SeBootstrap tests excluded from my run at the moment.
