### ISSUE TITLE
Clarify that java Se support in Section 2.3

### ISSUE THREAD

**Issue by jim-krueger** [jakartaee/rest#1127]
Currently Section 2.3 of the Jakarta RESTful Web Services Specification states the following:
`A compliant implementation MUST support both alternatives on Java SE.`

Via notes in the [rest-dev] mailing list I've confirmed that the consensus was that _"The Java SE Bootstrap API is mandatory for those compliant products that already provide a way to natively bootstrap on Java SE."_. [https://www.eclipse.org/lists/rest-dev/msg00008.html](https://www.eclipse.org/lists/rest-dev/msg00008.html)

Therefore I think that the statement above should be removed from section 2.3 and a new statement similar to the following be added to Section 2.3.1 Java SE:
```
There are two alternative ways of publishing on Java SE: Creating SE endpoints directly or using the SE bootstrap
API. Both are described in this section. Any compliant implementation that supports either of these alternatives on Java SE MUST support both.
```

**Comment by mkarg** [comment]
I always understood the existing sentence in that way, but I am not in the way of expressing the same more elaborately. :-)
