### ISSUE TITLE
TCK:  The ee.jakarta.tck.ws.rs.sebootstrap.SeBootstrapIT tests should be optional

### ISSUE THREAD

**Issue by jim-krueger** [jakartaee/rest#1128]
This request related to issue #1127 

Since the consensus is that the Java SE Bootstrap support added in Jakarta Restful Web Services 3.1 was intended to only be "_...mandatory for those compliant products that already provide a way to natively bootstrap on Java SE._", the ee.jakarta.tck.ws.rs.sebootstrap.SeBootstrapIT should be made to be optional.

One option would be to add these tests to the TCK-Exclude-List.txt file.

Another option would be to code these tests in such a way as to make them optional and update the TCK user guild to document how to configure things to prevent their execution.

**Comment by Emily-Jiang** [comment]
From the spec, the Java SE is optional for EE environment. The option to exclude this test sounds reasonable. Thoughts? @spericas @jansupol ?

**Comment by spericas** [comment]
Any comments @alwin-joseph?

**Comment by alwin-joseph** [comment]
IMO it would be better to add a new tag, (say "optional" or "se_optional") to the SeBootstrapIT tests and document the same to make them optional similar to how it was done for "servlet", "security" , "xml_binding" tagged tests. 
Disabling them (with `@Disabled`) will not let those tests to be run at all. 


> One option would be to add these tests to the TCK-Exclude-List.txt file.

The file is used only for documentation purpose and does not disable or exclude any test actually.

> Another option would be to code these tests in such a way as to make them optional and update the TCK user guild to document how to configure things to prevent their execution.

+1

cc @mkarg

**Comment by spericas** [comment]
@alwin-joseph I agree, I like the idea of using tags instead of disabling tests. Unless somebody objects, let's proceed with this option.

**Comment by mkarg** [comment]
+1 for using the new "se_bootstrap" tag

**Comment by Emily-Jiang** [comment]
> +1 for using the new "se_bootstrap" tag

+1
By the way, the service release can be started asap.
