### ISSUE TITLE
javax.ws.rs.core.StreamingOutput

### ISSUE THREAD

**Issue by hjaijhoussem** [jakartaee/rest#1148]
error : java.lang.ClassNotFoundException: javax.ws.rs.core.StreamingOutput 
I'm using 5.2.0 gitlab4j version

**Comment by chkal** [comment]
Looks like a missing dependency in your project. That's definitely not a spec issue.

**Comment by hjaijhoussem** [comment]
> Looks like a missing dependency in your project. That's definitely not a spec issue.

the error solved by using the latest version  of gitlab4j"6.0.0-rc.1"
