### ISSUE TITLE
How to pass jakarta.ws.rs.core.Response to a method accepting javax.ws.rs.core.Response

### ISSUE THREAD

**Issue by harpreet86** [jakartaee/rest#1151]
I have updated the version of the library `jakarta.ws.rs-api` from _2.1.6_ to _3.0.0_, this has changed the package of Response class from _javax.ws.rs.core_ to _jakarta.ws.rs.core_

Now my code uses a library that still accepts _javax.ws.rs.core.Response_ objects, this library might take time to switch to the new version of _jakarta.ws.rs-api_.

Any suggestions?

**Comment by spericas** [comment]
Please don't file an issue to ask a question. You cannot mix javax and jakarta packages, if you move to jakarta, all your libraries and dependencies need to be moved as well.
