### ISSUE TITLE
Proposal: Deprecate the ClientBuilder.hostnameVerifier method

### ISSUE THREAD

**Issue by jamezp** [jakartaee/rest#1161]
I propose we should deprecate the [`ClientBuilder.hostnameVerifier()`](https://jakarta.ee/specifications/restful-ws/3.1/apidocs/jakarta.ws.rs/jakarta/ws/rs/client/clientbuilder#hostnameVerifier(javax.net.ssl.HostnameVerifier)). The JDK HttpClient does not have a way to set this. It does allow this to be disabled, but it's a global setting which doesn't work well for the ClientBuilder. It could also be overridden with some custom HostnameVerifier, however that seems it could lead to security risks.

There is an open issue, [DK-8213309](https://bugs.openjdk.org/browse/JDK-8213309), to enable this. However, there has been no word from the JDK team to indicate they will add this.

My assumption is this override was added for testing or internal use cases. It seems like something that could be worked around in different ways or a safer manner.

**Comment by jansupol** [comment]
I am -1 on this one. First, even if this is not supported by the java.net.http.HttpClient, it does not mean it is not supported by other clients (HttpsUrlConnection, Apache, ...)

Jersey uses the HostNameVerifier with the HttpClient anyway,[ after the handshake](https://github.com/eclipse-ee4j/jersey/blob/2.x/connectors/jdk-connector/src/main/java/org/glassfish/jersey/jdk/connector/internal/SslFilter.java#L550).

**Comment by spericas** [comment]
@jamezp Should we close this one then?

**Comment by jamezp** [comment]
@spericas We can if no one else agrees they want it deprecated :)

**Comment by jamezp** [comment]
Closing this as it's not agreed upon which is fine.
