### ISSUE TITLE
TCK Challenge: ee.jakarta.tck.ws.rs.ee.rs.container.responsecontext.JAXRSClientIT#setEntityStreamTest

### ISSUE THREAD

**Issue by radcortez** [jakartaee/rest#1163]
The test uses the original stream to write into it with a new stream set on jakarta.ws.rs.container.ContainerResponseContext#setEntityStream. The specification details that the implementation must close the output stream, but in the way the test is written, the original stream should also be closed:

https://github.com/jakartaee/rest/blob/release-3.1.x/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/responsecontext/ResponseFilter.java#L300-L328

**Comment by spericas** [comment]
@alwin-joseph Could you evaluate this one?

**Comment by alwin-joseph** [comment]
@spericas Can you please mark this as accepted (As per https://jakarta.ee/committees/specification/tckprocess, if this challenge is accepted, the `accepted` label should be added to this issue and the issue closed, ref https://github.com/jakartaee/rest/issues/1162#issuecomment-1677759200 ).

We will work to exclude this test for 3.1.4 TCK

**Comment by spericas** [comment]
@alwin-joseph Done

**Comment by jamezp** [comment]
I don't have the permissions, but this should probably be closed now. https://github.com/jakartaee/specifications/pull/657 released the 3.1.4 TCK.

**Comment by spericas** [comment]
Resolved
