### ISSUE TITLE
JDK 21

### ISSUE THREAD

**Issue by mkarg** [jakartaee/rest#1167]
The Jakarta EE Platform 11 has a lower bound of JDK 21, so we need to raise bars a bit.

**Comment by jamezp** [comment]
FWIW the only spec I'm aware of with a minimum of Java 21 is concurrency. I don't really have a strong preference either way, but just wanted to point it out.

**Comment by rsearls** [comment]
It is my understanding that there *might* be concurrency changes
made in jdk-21 that could break old jdk code.  But that spec is
not yet finalized nor fully implemented in jdk-21.  James, do I
understand this correctly?

I think there are 2 considerations based on the current state of jdk-21.
How will this affect Wildfly and
3rd party customers that use the resteasy container separately.
As long as resteasy is not using some element unique to jdk-21
that prevents it from being run with jdk-17 or jdk-11 there should
be no concern for this change at this time.  Once the concurrency
changes are finalize and implemented we may need to re-evaluate
how to move forward.  Currently this seems like a low risk update
to me.
