### ISSUE TITLE
Error in multipart example

### ISSUE THREAD

**Issue by jim-krueger** [jakartaee/rest#1186]
The `jaxrs.examples.multipart.MultipartClient.sendPdfs()` contains the following code:

`        Entity<List<EntityPart>> entity = Entity.entity(parts, MediaType.MULTIPART_FORM_DATA);
        Response response = target.request().post(entity);
`

This causes a failure since there isn't a way to get the generic type for an ArrayList (`parts`).

Line 37 needs to be changed to:

`Entity<GenericEntity<List<EntityPart>>> entity = Entity.entity(new GenericEntity<>(parts){}, MediaType.MULTIPART_FORM_DATA);
`

**Comment by spericas** [comment]
@jansupol
