### ISSUE TITLE
Add "working branches" section to Committer-Conventions

### ISSUE THREAD

**Issue by jim-krueger** [jakartaee/rest#1219]
In an effort to allow for accelerated development and prototype work for the proposed release-3.2 effort I’d like to add the following section to our [Committer Conventions](https://github.com/jakartaee/rest/wiki/Committer-Conventions).    I initially sent this as a note in the mailing list and have made a few adjustments.

Please vote and/or add suggestions.

## Working Branches
Occasionally there may be a need for the community to collaborate and develop changes for the purposes of prototyping etc.   In those cases a “working branch” may be created that will be managed with exceptions to the conventions stated above:  

### What is a Working Branch?

- A working branch is a branch created for accelerated development and prototyping purposes
- A branch must receives 3 committer +1 votes (and no -1 votes) before being designated as a working branch.
- A working branch does not correspond directly to any documented release plan.
- Content in a working branch will need full approval via the Committer Conventions above before being added to the master/release/main branch or any branch corresponding to a documented release plan.

### Exceptions to Committer Conventions for Working Branches

(1) There will be no minimum wait time to merge / close PRs.

(2)  PRs may be merged / closed following review and approval by at least one committer (other than the submitter themself).

**Comment by jamezp** [comment]
+1 this makes sense to me.

**Comment by mkarg** [comment]
+-0: I do not have objections, but I do not _actively_ support any weakening of the committer rules.

**Comment by jim-krueger** [comment]
I don't see this as a weakening of the committer rules since any and all changes that would be placed in the master/main or any branch corresponding to an active release plan would need to follow the established committer rules.   This would only be allowing our group to collaborate quickly on a separate working branch.  An advantage being that the group will be exposed to the prototyping work being done, rather than having those involved working separately to avoid being held up by the current process.

**Comment by jansupol** [comment]
+0: I can see the urge for this for 3.2, but for other non-urged branches I feel relaxed about having extra time, especially during the summer vacation time.

**Comment by jim-krueger** [comment]
> I can see the urge for this for 3.2, but for other non-urged branches I feel relaxed about having extra time, especially during the summer vacation time.

@jansupol I've added the following above.  Does that possibly change your vote?

> - A branch must receives 3 committer +1 votes (and no -1 votes) before being designated as a working branch.

**Comment by jansupol** [comment]
+1 if there is a list of current working branches, possibly in the Readme or on Wiki

**Comment by jim-krueger** [comment]
>  if there is a list of current working branches, possibly in the Readme or on Wiki
Good idea.   As soon as this passes I will add a list to the wiki and add a link to it in the Committer Conventions.

**Comment by asoldano** [comment]
+1, this looks ok to me

**Comment by jim-krueger** [comment]
So for there have been 3 - +1 votes including two committers beyond myself and 1 - 0 votes.  If there are no -1 votes by next Tuesday (February 20th) I will add the above to our [Committer Conventions](https://github.com/jakartaee/rest/wiki/Committer-Conventions).   Thanks

**Comment by jimma** [comment]
+1, this looks good .

**Comment by spericas** [comment]
+1

**Comment by jim-krueger** [comment]
I've added the new section to the [Committer Conventions](https://github.com/jakartaee/rest/wiki/Committer-Conventions).

Closing issue
