### ISSUE TITLE
Designate the release-3.2 branch as a "working branch"

### ISSUE THREAD

**Issue by jim-krueger** [jakartaee/rest#1222]
Assuming the changes proposed in issue #1219 are accepted I would like to designate the current **release-3.2** branch as a working branch to allow prototyping of @Context deprecation to proceed at an increased rate.

Per the new process, 3 committer votes are required to designate a branch as a "working branch" so please vote.

Please note that (per the process) changes introduced in the release-3.2 branch will still need to go through a full review cycle prior to being incorporated into master/main.

Thanks

**Comment by jansupol** [comment]
+1

**Comment by jamezp** [comment]
+1 (non-binding)

**Comment by mkarg** [comment]
+-0 Nothing against it, but not actively supporting it.

**Comment by asoldano** [comment]
+1, thanks

**Comment by jim-krueger** [comment]
Since this has received the 3 committer votes required by the working branch [committer conventions](https://github.com/jakartaee/rest/wiki/Committer-Conventions).  It is now listed as a working branch on the [Jakarta Rest Wiki](https://github.com/jakartaee/rest/wiki/Jakarta-Rest-Working-Branches).  

Closing this issue
