### ISSUE TITLE
General ExceptionMapper<Throwable> not working for all exceptions in Quarkus

### ISSUE THREAD

**Issue by joe-specimen** [jakartaee/rest#1302]
I have implemented following general ExceptionMapper<Throwable>:

```java
@Provider
@JBossLog
public class RestExceptionMapper implements ExceptionMapper<Throwable> {

   @Override
   public Response toResponse(Throwable exception) {
      final Throwable rootCause = ExceptionUtils.getRootCause(exception);
      log.errorf("General exception: %s", rootCause.getMessage(), rootCause);
      return Response.status(Status.INTERNAL_SERVER_ERROR).build();
   }
}
```
And I have implemented following REST resource:

```java
@Path("/process-settings")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class ProcessSettingResource {

    @POST
    @RunOnVirtualThread
    public RestResponse<Object> createProcessSetting(
        @Valid CreateProcessSettingDto processSettingDto,
        @Context UriInfo uriInfo
    ) {
        URI location = uriInfo.getAbsolutePathBuilder()
            .path(String.valueOf(1L))
            .build();

        if (processSettingDto.getProcessInfo().getProcessName().equals("FAIL")) {
            // ResteasyReactiveViolationException is NOT handled by RestExceptionMapper
            throw new ResteasyReactiveViolationException("Process Name is invalid", new HashSet<>());

            // RuntimeException IS handled by RestExceptionMapper
            // throw new RuntimeException("Process Name is invalid");

            // IllegalArgumentException IS handled by RestExceptionMapper
            // throw new IllegalArgumentException("Process Name is invalid");
        }

        return ResponseBuilder.create(Status.CREATED).location(location).build();
    }
}
```
Can somebody explain me why certain exceptions are not handled by the general ExceptionMapper<Throwable> like `ResteasyReactiveViolationException` or its super class `ConstraintViolationException` and some of them are handled by the general ExceptionMapper<Throwable> like `RuntimeException`, `IllegalArgumentException`. 
Can somebody explain me if this is a bug or a feature?
If it is a feature can you tell me where are these rules written?

**Comment by NicoNes** [comment]
Hey @joe-specimen,

I'm not sure you are on the right place here for this question/issue. Maybe you should try this github page instead : https://github.com/quarkusio/quarkus/.  
Also I suggest you to have a look to [this issue](https://github.com/quarkusio/quarkus/issues/7883) and [this PR](https://github.com/quarkusio/quarkus/pull/32425), that look close to your issue.

-- Nicolas

**Comment by joe-specimen** [comment]
@NicoNes . Thanks for the advice 👍. It is exactly what I was looking for. I will close this issue here.
