### ISSUE TITLE
HTTP "Server Push"

### ISSUE THREAD

**Issue by scholzi100** [jakartaee/rest#923]
Recently I used Jax-RS with HTTP/2 quite a bit. I also had a quick dive into Server-Sent Event (SSE).
As much as I can tell, HTTP Server Push does quite the same as SSE but SSE relies on" messages" send over the wire and Server Push on HTTP Frames (aka HTTP Responces).
 
For me it seams to be a better solution to relay on Server Push as of HTTP/2, since it does provide better integration in the sence of HTTP context. It also provides the ability to send standardized binary types because of the Context-Type header in the Responce, which SSE is not able to (see #889).

Are there plans to support this HTTP feature in some future version? (maybe 4.0)

---
Server push is also supported with the Java 9 [HTTP Client API](http://openjdk.java.net/jeps/110) using the [PushPromiseHandler](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpResponse.PushPromiseHandler.html).

- [RFC7540 HTTP/2 Server push](https://tools.ietf.org/html/rfc7540#section-8.2)
- [Draft 32 HTTP/3 Server push](https://tools.ietf.org/html/draft-ietf-quic-http-32#section-4.4)
- [Server-Sent Events](https://www.w3.org/TR/eventsource/)

**Comment by mkarg** [comment]
HTTP/2 is definitively an interesting issue for the future. The problem with JAX-RS is that it is just common API above existing products. So you gain nothing just by adopting HTTP/2 in JAX-RS. What you need in the first place are commitments by the product vendors that they will adopt HTTP/2 in their products. So the actual question goes to Apache, IBM, RedHat and Oracle: Will you support HTTP/2 server push and in what time frame? @deki @andymc12 @ronsigal @jansupol

**Comment by deki** [comment]
In Apache CXF we have an open issue for many years https://issues.apache.org/jira/browse/CXF-6349 but no concrete time frame yet.

**Comment by spericas** [comment]
Although in both SSE and Server Push, data is being _pushed_ to the client, I don't think the intent of these technologies is really the same. Server Push was primarily designed to get around _hacks_ people were doing with HTTP/1 to optimize page downloads, while SSE was designed to get around _other hacks_ like long polling. 

These two technologies don't really sit at the same abstraction layer, and certainly operate with a different set of concepts. For example, a `PushPromiseHandler` is really designed to handle the page download use case: "A push promise request may be received up to the point where the response body of the initiating client-sent request has been fully received". In my view, some of these design decisions in Server Push don't really align with SSE's.

**Comment by jansupol** [comment]
I might be wrong, but if Servlet 4 already supports HTTP/2, and [Server Push](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/PushBuilder.html), so can JAX-RS.

**Comment by spericas** [comment]
@jansupol Yes, they do, but for the Server Push use case of pushing resource dependencies AFAIK. As I see it, more of a _web server_ feature than a _REST feature_.

**Comment by chkal** [comment]
Partially related: The Chrome team [announced in early November](https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1), that they will remove Server Push from their HTTP/2 and HTTP/3 protocol implementations. See also this [blog post](https://evertpot.com/http-2-push-is-dead/) for some context.

Of course this decision shouldn't be a blocker for us, but it may be a hint about the current popularity of this feature and the actual need for standardization.

**Comment by mkarg** [comment]
Latest information: https://developer.chrome.com/blog/removing-push/

Actually Chrome is one of the most used browser, so the question is: Does it still make sense to add Server Push to JAX-RS, if Chrome does not support it anymore?

**Comment by chkal** [comment]
I think that this is a sign that Server Push isn't widely adopted, and therefore I don't think that working on an API for this feature makes a lot of sense to be honest.

**Comment by spericas** [comment]
I agree with the last few comments. Closing this issue.
