### ISSUE TITLE
Fix JavaDoc Warnings

### ISSUE THREAD

**Issue by mkarg** [jakartaee/rest#979]
There are several JavaDoc warnings in `examples` and `jaxrs-api` sources.

**This is a good newcomer's issue.**

**Comment by andygibson** [comment]
Submitted PRs #984 , #985 and #986

**Comment by chkal** [comment]
@andygibson Thanks a lot! Looks great!

**Comment by mkarg** [comment]
There are new JavaDoc warnings. Maybe one of our new contributors like to fix it for 3.1? :-)

```
5 warnings
[WARNING] Javadoc Warnings
[WARNING] /workspace/jaxrs-api/jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java:137: warning: @param "T" has already been specified
[WARNING] * @param <T> the entity type
[WARNING] ^
[WARNING] /workspace/jaxrs-api/jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java:176: warning: @param "T" has already been specified
[WARNING] * @param <T> the entity type
[WARNING] ^
[WARNING] /workspace/jaxrs-api/jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java:322: warning: @param "T" has already been specified
[WARNING] * @param <T>     the entity type
[WARNING] ^
[WARNING] /workspace/jaxrs-api/jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java:349: warning: @return has already been specified
[WARNING] * @return the updated builder.
[WARNING] ^
[WARNING] /workspace/jaxrs-api/jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java:374: warning: @param "T" has already been specified
[WARNING] * @param <T> the entity type
[WARNING] ^
```

**Comment by mkarg** [comment]
@jelemux Like to fix this one? :-)

**Comment by jelemux** [comment]
@mkarg  Yes, I do. I'll see if I can find some time for it over the weekend.

**Comment by mkarg** [comment]
@jelemux Is preparing a PR for this. Thank you, Jeremias! :-)

**Comment by jelemux** [comment]
Submitted PR #1028

---

Also, what is to be done about the issue I mentioned?

> What maybe should be addressed as well are the JavaDoc Errors in `jaxrs-tck`.  
There are lots of errors because the code just got ported and focus was on the migration.  
Maybe we don't need to generate JavaDoc for this at all though and it can be excluded? WDYT?  
Should this be discussed in a seperate PR / issue?

**Comment by mkarg** [comment]
@spericas @andymc12 @chkal @jansupol There are no more warnings in the API itself, but there are 100+ warnings in the Examples and TCK. To not further delay publication of 3.1, I'd like to propose that I do split this issue, i.e. I do close this one and reopen two separate issues for Examples and TCK which we resolve in 4.0. WDYT?

**Comment by spericas** [comment]
@mkarg As you suggested, closing this one. Let's reopen one for 4.0.
